name: protobuf
version: 0.2.0+2
authors:
- Dart Team <misc@dartlang.org>
description: Runtime library for protobuf support.
homepage: https://github.com/dart-lang/protobuf
environment:
  sdk: '>=0.7.5'
dependencies:
  crypto: '>=0.7.5'
  fixnum: '>=0.7.5'
dev_dependencies:
  unittest: any
