name: protoc_plugin
version: 0.5.0
author: Dart Team <misc@dartlang.org>
description: Protoc compiler plugin to generate Dart code
homepage: https://github.com/dart-lang/dart-protoc-plugin
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  protobuf: '>= 0.5.0 <0.6.0'
  path: '>=1.0.0 <2.0.0'
dev_dependencies:
  browser: any
  test: '>=0.12.0 <0.13.0'
