name: protoc-plugin
version: 0.2.0
authors:
- Dart Team <misc@dartlang.org>
description: Protoc compile to generate Dart code
homepage: https://github.com/dart-lang/protoc-plugin
environment:
  sdk: '>=0.7.5'
dependencies:
  protobuf: '>=0.2.0+2'
dev_dependencies:
  unittest: any
