name: protoc-plugin
version: 0.2.1
authors:
- Dart Team <misc@dartlang.org>
description: Protoc compiler plugin to generate Dart code
homepage: https://github.com/dart-lang/protoc-plugin
environment:
  sdk: '>=0.8.5'
dependencies:
  protobuf: '>=0.3.1'
dev_dependencies:
  unittest: any
